typedef struct _trkNo {
    ushort  trkNo1;
    ushort  trkNo2;
    uint    trkNo3;
    uint    trkNo4;
} trkNo;

struct EIE_header {         // 26
    trkNo   srcTN;          // 12
    trkNo   dstTN;          // 12
    ushort   msgType;       // 2
}
 typedef struct _EIE_0xD001 {
uint type1[39];

} EIE_0xD001;



struct EIE_0xD010 {
ushort type1[200];
ushort type2 [300];
ushort type3;
ushort type4;
ushort type5;
ushort type6;
ushort type7;
ushort type8;
ushort type9;
ushort type10;
}

struct EIE_0x0301{
EIE_header  header;
uchar	type1;  // 0~200
ushort type2;
}

struct EIE_0x0302{
EIE_header  header;
uint	type1;
ushort type2;
uchar type3;
int 	type4;
short type5;
char type6;
}

struct EIE_0x0303{
EIE_header  header;
uint	type1;
ushort type2;
uchar type3;
int 	type4;
short type5;
char type6;
}