typedef struct _trkNo {
    ushort  trkNo1;
    ushort  trkNo2;
    uint    trkNo3;
    uint    trkNo4;
    uchar    trkNo5;
    int     trkNo6;
} trkNo;

struct EIE_header {         // 26
    trkNo   srcTN [2];          // 12
    trkNo   dstTN[2];          // 12
    ushort   msgType;       // 2
}
 typedef struct _EIE_0xD001 {
uint type1[39];

} EIE_0xD001;

struct EIE_0xD010 {
ushort type1[5];
ushort type2 [5];
}

struct EIE_0x0301{
EIE_header  header;
uchar	type1;  // 0~200
ushort type2;
}

struct EIE_0x0302{
EIE_header  header;
uint	type1;
ushort type2;
uchar type3;
int 	type4;
short type5;
char type6;
}
/*
struct EIE_0x0303{
EIE_header  header;
uint	type1;
ushort type2;
uchar type3;
int 	type4;
short type5;
char type6;
}
*/

struct strHeader  {
	ushort type;
	ushort size;
	uchar id;
	uchar unit;	// 1, 2, 3, 4, 5, 6, 7, 240
};

struct trkNoSys	 { 
	ushort	trkNo;
	ushort	trkNo_MDIL;	// 0~65023 
	ushort	trkNo_TDIL_B;	// 0, 1~62, 64~4094 
	uchar	trkNoMITS;
	uchar	trkNoMFR;
	int		trkNo_TDIL_J;	// 0~524287
};

struct EIE_0x70F3  { 
	strHeader	header;
	ushort	statusId;
	char		statusString[41];	// string
}; 