//Header for TIE
typedef struct _TIE_HEADER {
	octet MESSAGE_LEVEL;
	octet MESSAGE_SUBLEVEL;
	unsigned short MESSAGE_LENGTH;
	octet ORIGINATOR;
	octet SEQUENCE_NUMBER;
} TIE_HEADER;

struct IEM_SYS_005 {
	TIE_HEADER HEADER_FRAME;

	unsigned short CBIT_RESULT;             //0~65535
};