# Form implementation generated from reading ui file 'dialog_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewerWindow(object):
    def setupUi(self, ViewerWindow):
        ViewerWindow.setObjectName("ViewerWindow")
        ViewerWindow.resize(1028, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewerWindow.sizePolicy().hasHeightForWidth())
        ViewerWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=ViewerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.list_csv_names = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_csv_names.sizePolicy().hasHeightForWidth())
        self.list_csv_names.setSizePolicy(sizePolicy)
        self.list_csv_names.setMinimumSize(QtCore.QSize(100, 0))
        self.list_csv_names.setMaximumSize(QtCore.QSize(100, 16777215))
        self.list_csv_names.setObjectName("list_csv_names")
        self.gridLayout.addWidget(self.list_csv_names, 0, 0, 1, 1)
        self.table_csv = QtWidgets.QTableView(parent=self.centralwidget)
        self.table_csv.setStyleSheet("")
        self.table_csv.setObjectName("table_csv")
        self.gridLayout.addWidget(self.table_csv, 0, 1, 1, 1)
        ViewerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ViewerWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewerWindow)

    def retranslateUi(self, ViewerWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewerWindow.setWindowTitle(_translate("ViewerWindow", "MainWindow"))
