# Form implementation generated from reading ui file 'dialog_viewer_backup.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewerWindow(object):
    def setupUi(self, ViewerWindow):
        ViewerWindow.setObjectName("ViewerWindow")
        ViewerWindow.resize(1093, 761)
        self.gridLayout_2 = QtWidgets.QGridLayout(ViewerWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.list_csv_names = QtWidgets.QListWidget(parent=ViewerWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_csv_names.sizePolicy().hasHeightForWidth())
        self.list_csv_names.setSizePolicy(sizePolicy)
        self.list_csv_names.setMinimumSize(QtCore.QSize(130, 0))
        self.list_csv_names.setMaximumSize(QtCore.QSize(130, 16777215))
        self.list_csv_names.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.list_csv_names.setAcceptDrops(False)
        self.list_csv_names.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.list_csv_names.setObjectName("list_csv_names")
        self.gridLayout_2.addWidget(self.list_csv_names, 3, 0, 1, 1)
        self.table_csv = QtWidgets.QTableView(parent=ViewerWindow)
        self.table_csv.setStyleSheet("QTableView::verticalHeader {background-color: lightgray; width: 50px;\n"
"                                                                    border: 1px solid black;}\n"
"\n"
"QTableView::verticalHeader {background-color: lightgray; width: 50px;\n"
"                                                                    border: 1px solid black;}")
        self.table_csv.setObjectName("table_csv")
        self.table_csv.verticalHeader().setVisible(True)
        self.table_csv.verticalHeader().setDefaultSectionSize(20)
        self.table_csv.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_2.addWidget(self.table_csv, 3, 1, 1, 1)
        self.frame = QtWidgets.QFrame(parent=ViewerWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 31))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 31))
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(776, 10, 160, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(160, 20))
        self.lineEdit.setSizeIncrement(QtCore.QSize(160, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.frame, 2, 1, 1, 1)

        self.retranslateUi(ViewerWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewerWindow)

    def retranslateUi(self, ViewerWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewerWindow.setWindowTitle(_translate("ViewerWindow", "CSV Viewer"))
