# Form implementation generated from reading ui file 'dialog_filter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FilterForm(object):
    def setupUi(self, FilterForm):
        FilterForm.setObjectName("FilterForm")
        FilterForm.resize(176, 65)
        FilterForm.setMaximumSize(QtCore.QSize(400, 400))
        FilterForm.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.formLayout = QtWidgets.QFormLayout(FilterForm)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(parent=FilterForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.frame)
        self.button_close = QtWidgets.QPushButton(parent=FilterForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(80, 0))
        self.button_close.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_close.setObjectName("button_close")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.button_close)
        self.button_apply = QtWidgets.QPushButton(parent=FilterForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_apply.sizePolicy().hasHeightForWidth())
        self.button_apply.setSizePolicy(sizePolicy)
        self.button_apply.setMinimumSize(QtCore.QSize(80, 0))
        self.button_apply.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_apply.setObjectName("button_apply")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.button_apply)

        self.retranslateUi(FilterForm)
        QtCore.QMetaObject.connectSlotsByName(FilterForm)

    def retranslateUi(self, FilterForm):
        _translate = QtCore.QCoreApplication.translate
        FilterForm.setWindowTitle(_translate("FilterForm", "Form"))
        self.button_close.setText(_translate("FilterForm", "Close"))
        self.button_apply.setText(_translate("FilterForm", "Apply"))
